---
stages:
  - test

image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  ROLE_NAME: linux-motd
  MOLECULE_DISTRO: debian9

services:
  - docker:dind

test:
  image: ubuntu:18.04
  stage: test
  script:
    - apt-get update && apt-get install -y make python virtualenv gcc python-dev docker.io python-pip
    - pip install molecule docker testinfra
    - cd ../
    - cp -R ansible-role-$ROLE_NAME $ROLE_NAME
    - cd $ROLE_NAME
    - molecule --version
    - ansible --version
    - molecule test
